/**
 * Pixel dimensions of captured PNGs — regenerated by `npm run capture-flow-screens`.
 */
export const FLOW_SCREEN_DIMENSIONS: Record<string, { width: number; height: number }> = {
  "welcome": {
    "width": 720,
    "height": 1560
  },
  "signup": {
    "width": 720,
    "height": 1560
  },
  "verify-email": {
    "width": 720,
    "height": 1560
  },
  "welcome-signup": {
    "width": 720,
    "height": 1560
  },
  "login": {
    "width": 720,
    "height": 1560
  },
  "forgot-password": {
    "width": 720,
    "height": 1560
  },
  "reset-password": {
    "width": 720,
    "height": 1560
  },
  "profile-setup": {
    "width": 720,
    "height": 1652
  },
  "dashboard-new": {
    "width": 720,
    "height": 1980
  },
  "dashboard-returning": {
    "width": 720,
    "height": 3042
  },
  "dashboard-trends": {
    "width": 720,
    "height": 1560
  },
  "active-session": {
    "width": 720,
    "height": 1560
  },
  "sessions-list": {
    "width": 720,
    "height": 1560
  },
  "session-detail": {
    "width": 720,
    "height": 1826
  },
  "session-edit": {
    "width": 720,
    "height": 2700
  },
  "community": {
    "width": 720,
    "height": 2170
  }
};

export function frameHeightForScreen(screenId: string, nodeWidth: number, minHeight: number): number {
  const dims = FLOW_SCREEN_DIMENSIONS[screenId];
  if (!dims?.width) return minHeight;
  const scaled = Math.round((dims.height / dims.width) * nodeWidth);
  return Math.max(minHeight, scaled);
}
