/**
 * Pixel dimensions of captured PNGs — regenerated by flow-map capture.
 */
export const FLOW_SCREEN_DIMENSIONS: Record<string, { width: number; height: number }> = {
  "welcome": {
    "width": 720,
    "height": 1560
  },
  "signup": {
    "width": 720,
    "height": 1560
  },
  "verify-email": {
    "width": 720,
    "height": 1560
  },
  "welcome-signup": {
    "width": 720,
    "height": 1560
  },
  "login": {
    "width": 720,
    "height": 1560
  },
  "forgot-password": {
    "width": 720,
    "height": 1560
  },
  "reset-password": {
    "width": 720,
    "height": 1560
  },
  "profile-setup": {
    "width": 720,
    "height": 1890
  },
  "dashboard-new": {
    "width": 720,
    "height": 1560
  },
  "dashboard-profile-ready": {
    "width": 720,
    "height": 1986
  },
  "dashboard-returning": {
    "width": 720,
    "height": 3048
  },
  "dashboard-trends": {
    "width": 720,
    "height": 3178
  },
  "dashboard-one-session": {
    "width": 720,
    "height": 2678
  },
  "dashboard-many-sessions": {
    "width": 720,
    "height": 3956
  },
  "dashboard-mid-session": {
    "width": 720,
    "height": 2402
  },
  "active-session": {
    "width": 720,
    "height": 1588
  },
  "active-session-empty": {
    "width": 720,
    "height": 1560
  },
  "active-session-empty-incomplete": {
    "width": 720,
    "height": 1606
  },
  "active-session-adding-climb": {
    "width": 720,
    "height": 2604
  },
  "active-session-multi-climbs": {
    "width": 720,
    "height": 4832
  },
  "active-session-end-sheet": {
    "width": 720,
    "height": 4832
  },
  "active-session-end-sheet-filled": {
    "width": 720,
    "height": 4832
  },
  "sessions-list": {
    "width": 720,
    "height": 1560
  },
  "session-detail": {
    "width": 720,
    "height": 2304
  },
  "session-edit": {
    "width": 720,
    "height": 2938
  },
  "community": {
    "width": 720,
    "height": 2288
  }
};

export function frameHeightForScreen(
  screenId: string,
  nodeWidth: number,
  minHeight: number,
  extraDimensions?: Record<string, { width: number; height: number }>,
): number {
  const dims = extraDimensions?.[screenId] ?? FLOW_SCREEN_DIMENSIONS[screenId];
  if (!dims?.width) return minHeight;
  const scaled = Math.round((dims.height / dims.width) * nodeWidth);
  return Math.max(minHeight, scaled);
}
