import { DEFAULT_LEVEL_COLORS } from './difficultyLevels';
import type { ClimbingSession } from '../types/climbingSession';

export function createDemoSessions(homeLocationId: string, homeLocationName: string): ClimbingSession[] {
  const levels = DEFAULT_LEVEL_COLORS.slice(0, 5);
  return [
    {
      id: 'demo-session-1',
      status: 'completed',
      date: '2026-06-18',
      startTime: '18:00',
      endTime: '20:30',
      durationMinutes: 150,
      locationId: homeLocationId,
      locationName: homeLocationName,
      isPublic: false,
      ownerUsername: 'member',
      ownerAvatar: '🪨',
      climbs: [
        {
          id: 'c1',
          levelId: 'demo-level-0',
          levelName: levels[0].name,
          levelColor: levels[0].color,
          name: 'Slab warmup',
          tags: ['slab'],
          notes: 'Easy footwork',
          hasImage: false,
          hasVideo: false,
          isWarmUp: true,
          isRepeat: false,
          isProject: false,
          attempts: [{ id: 'a1', progress: ['send'] }],
        },
        {
          id: 'c2',
          levelId: 'demo-level-2',
          levelName: levels[2].name,
          levelColor: levels[2].color,
          name: 'Dyno corner',
          tags: ['dyno', 'overhang'],
          notes: '',
          hasImage: true,
          hasVideo: false,
          isWarmUp: false,
          isRepeat: false,
          isProject: false,
          attempts: [
            { id: 'a2', progress: ['start', 'middle'] },
            { id: 'a3', progress: ['flash'] },
          ],
        },
        {
          id: 'c3',
          levelId: 'demo-level-3',
          levelName: levels[3].name,
          levelColor: levels[3].color,
          name: 'Orange project',
          tags: ['crimpy'],
          notes: 'Hip tension',
          hasImage: false,
          hasVideo: true,
          isWarmUp: false,
          isRepeat: true,
          isProject: true,
          attempts: [
            { id: 'a4', progress: ['start'] },
            { id: 'a5', progress: ['middle'] },
            { id: 'a6', progress: ['end'] },
          ],
        },
      ],
    },
    {
      id: 'demo-session-2',
      status: 'completed',
      date: '2026-06-10',
      startTime: '17:30',
      endTime: '19:00',
      durationMinutes: 90,
      locationId: homeLocationId,
      locationName: homeLocationName,
      isPublic: true,
      ownerUsername: 'member',
      ownerAvatar: '🪨',
      climbs: [
        {
          id: 'c4',
          levelId: 'demo-level-1',
          levelName: levels[1].name,
          levelColor: levels[1].color,
          name: 'Blue traverse',
          tags: ['balance'],
          notes: '',
          hasImage: false,
          hasVideo: false,
          isWarmUp: true,
          isRepeat: false,
          isProject: false,
          attempts: [{ id: 'a7', progress: ['send'] }],
        },
        {
          id: 'c5',
          levelId: 'demo-level-4',
          levelName: levels[4].name,
          levelColor: levels[4].color,
          name: 'Comp wall',
          tags: ['power'],
          notes: '',
          hasImage: false,
          hasVideo: false,
          isWarmUp: false,
          isRepeat: false,
          isProject: false,
          attempts: [{ id: 'a8', progress: ['send'] }],
        },
      ],
    },
  ];
}

export const MOCK_PUBLIC_SESSIONS: ClimbingSession[] = [
  {
    id: 'public-1',
    status: 'completed',
    date: '2026-06-19',
    startTime: '19:00',
    endTime: '21:00',
    durationMinutes: 120,
    locationId: 'urban-climb',
    locationName: 'Urban Climb West End, Montague Rd Brisbane',
    isPublic: true,
    ownerUsername: 'alex_climber',
    ownerAvatar: '🪨',
    climbs: [
      {
        id: 'pc1',
        levelName: 'Blue',
        levelColor: '#4A90D9',
        name: 'Corner crack',
        tags: ['crimpy'],
        notes: '',
        hasImage: true,
        hasVideo: false,
        isWarmUp: false,
        isRepeat: false,
        isProject: false,
        attempts: [{ id: 'pa1', progress: ['send'] }],
      },
      {
        id: 'pc2',
        levelName: 'Purple',
        levelColor: '#9B59B6',
        name: 'Roof dyno',
        tags: ['dyno'],
        notes: '',
        hasImage: false,
        hasVideo: true,
        isWarmUp: false,
        isRepeat: false,
        isProject: false,
        attempts: [{ id: 'pa2', progress: ['flash'] }],
      },
    ],
  },
  {
    id: 'public-2',
    status: 'completed',
    date: '2026-06-18',
    startTime: '16:00',
    endTime: '17:30',
    durationMinutes: 90,
    locationId: 'kangaroo-point',
    locationName: 'Kangaroo Point Cliffs',
    isPublic: true,
    ownerUsername: 'thegoat',
    ownerAvatar: '🗿',
    climbs: [
      {
        id: 'pc3',
        levelName: 'Orange',
        levelColor: '#E67E22',
        name: 'River wall traverse',
        tags: ['slab', 'balance'],
        notes: '',
        hasImage: false,
        hasVideo: false,
        isWarmUp: false,
        isRepeat: false,
        isProject: false,
        attempts: [{ id: 'pa3', progress: ['flash'] }],
      },
    ],
  },
  {
    id: 'public-3',
    status: 'completed',
    date: '2026-06-17',
    startTime: '18:30',
    endTime: '20:00',
    durationMinutes: 90,
    locationId: 'urban-climb',
    locationName: 'Urban Climb West End',
    isPublic: true,
    ownerUsername: 'crimp_queen',
    ownerAvatar: '💎',
    climbs: [
      {
        id: 'pc4',
        levelName: 'Orange',
        levelColor: '#E67E22',
        name: 'Comp qualifier',
        tags: ['power', 'overhang'],
        notes: 'Still working the crux',
        hasImage: false,
        hasVideo: false,
        isWarmUp: false,
        isRepeat: false,
        isProject: true,
        attempts: [
          { id: 'pa4', progress: ['start'] },
          { id: 'pa5', progress: ['middle', 'end'] },
        ],
      },
    ],
  },
];
